name: task-a cd

on:
  pull_request:
    paths:
      - task_a/**

jobs:
  test:
    runs-on: "ubuntu-latest"
    name: pytest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
            cache: 'pip'
        - name: Install dependencies with cache
          run: |
            pip install -r ./task_a/requirements.txt
        - name: Run tests for task_a
          run: pytest ./task_a/task_a.py